name: 'Cloudflare'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Every day, at 9 AM

permissions:
  contents: read

jobs:
  adblock_terraform:
    name: 'Adblock - Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: cloudflare/ad_block

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.14.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
